### ISSUE TITLE
Preloading when used with Vue/Vite/Rollup

### ISSUE THREAD

**Issue by toptensoftware** [marella/material-symbols#10]
Just wondering if you have any suggestions on how to preload these fonts when packaged by vue/vite/rollup.

I've posted a [general question about it here](https://stackoverflow.com/questions/74595366/preloading-imported-fonts-in-vue3-vite-rollup), but thought you might have some ideas.

**Comment by marella** [comment]
Haven't used them before but found this plugin for webpack: https://github.com/vuejs/preload-webpack-plugin. It is also mentioned in Vue CLI docs [here](https://cli.vuejs.org/guide/html-and-static-assets.html#preload).
Another plugin for vite: https://github.com/Applelo/vite-plugin-inject-preload
