### ISSUE TITLE
Support named exports

### ISSUE THREAD

**Issue by AnonymusRaccoon** [marella/material-symbols#11]
Hello,

Would it be possible to add an index file that would export all svgs using a named export? That would allow us to import them like
```javascript
import { Face } from '@material-design-icons/svg/filled';
```

This would also autocomplete imports which is quite nice to have.

**Comment by marella** [comment]
Hi, adding an index file with all SVGs will significantly increase the package size. Also it wouldn't be useful for frameworks like React. For example, you can import an SVG file as React Component (see [example](https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs)) but it wouldn't be possible with a index file.
So I would prefer to keep it simple and not add it.
