### ISSUE TITLE
When to use this? (since it seems to be 2.9mb)

### ISSUE THREAD

**Issue by silveltman** [marella/material-symbols#14]
I read some things about self hosting fonts for performance en thought, why not try it with an icon font aswell.
Using the symbols this way doesn't seem like a good idea when looking at the size.

![image](https://user-images.githubusercontent.com/52583398/215294697-b815da14-5507-43ab-b199-8bea5414bb67.png)

This raises the question for me, when should this package be used?

**Comment by austinw-fineart** [comment]
The large size likely has to do with the variable font support:
https://developers.google.com/fonts/docs/material_symbols

If you try downloading the fonts from https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined
you'll notice that the size is much more in line with Material Icons. This is a static version of the font with only the default configuration. I think the npm package could include static versions of the fonts, but be aware that you'll lose out on variable font support.

**Comment by marella** [comment]
Sorry for the late response. I don't think self hosting improves performance. Self hosting is required in the following cases: app should work offline, organization policies don't allow serving content from third party domains, you have users in countries where Google domains are blocked etc. So if you have a requirement for self hosting then this package will be useful.

As mentioned by austinw-fineart, the large size is due to variable fonts with different variations (fill, weight, grade, and optical size). I'm thinking of creating a lighter version of variable fonts with fewer variations (fill, weight) which can reduce the size by 70%.

**Comment by m-blank** [comment]
If you only want to use certain features of this variable font, you can try modifying the URL @austinw-fineart linked. For example, I only need the optical size axis (opsz) from 24 to 48 and a weight (wght) of 400:

https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght@24..48,400
The resulting file is only 477 KB in size.

There are 4 possible axes (opsz, wght, FILL, GRAD), which must be separated by commas. They are followed by an @ sign and then by the value ranges for the respective axes.

Another example:
https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-25..200

**Comment by unvented** [comment]
I'm using the static font for now, with e.g. `Fill: 0 Weight: 300 Grade: 0 Optical Size: 48` I get [this stylesheet](https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,300,0,0) and the referenced .woff2 file has a size of <300 kB.

I'd appreciate it tho to have a additional file for each style included in the package or in a separate one under the `@material-symbols` scope. It should be as basic as the static font with the grade and optical size left unchanged.

**Comment by marella** [comment]
Published lighter version of variable fonts (only `FILL `can be changed) with different weights to separate packages ([@material-symbols/font-400](https://www.npmjs.com/package/@material-symbols/font-400) for weight 400 etc.). Each font file size is ~300-350KB.
