### ISSUE TITLE
Some icons that exist in the font are not included in the svgs

### ISSUE THREAD

**Issue by jgnewman** [marella/material-symbols#17]
Two examples I've noticed are `pill` and `stethoscope`. Is this an issue on Google's side or a bug in this repo?

**Comment by marella** [comment]
Both icons are present in SVGs:

- https://github.com/marella/material-symbols/blob/main/svg/400/outlined/pill.svg
- https://github.com/marella/material-symbols/blob/main/svg/400/outlined/stethoscope.svg

Please check if you are using the latest version (0.5.5) of [@material-symbols/svg-400](https://www.npmjs.com/package/@material-symbols/svg-400)

**Comment by jgnewman** [comment]
Ah you were right. Sorry, just a dumb mistake on our part over here.
