### ISSUE TITLE
Is there a reason all viewbox values are set so high? Every icon's viewbox is "0 96 960 960"

### ISSUE THREAD

**Issue by fmotion1** [marella/material-symbols#18]
Are there any plans to update the icons with a viewbox that corresponds to the icon's size?

**Comment by marella** [comment]
These values are set by Google on https://fonts.google.com/icons and this repo doesn't modify them if already set. For example, see the source of https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/search/default/48px.svg

I was about to suggest reporting on official repo but looks like you already did that in https://github.com/google/material-design-icons/issues/1523

Closing this issue as it is already reported on official repo.
