### ISSUE TITLE
Include `_data/versions.json` in the package

### ISSUE THREAD

**Issue by tzkuei** [marella/material-symbols#4]
Please include `_data/versions.json` in the package so we have access to all the icon names.

**Comment by marella** [comment]
Can you please mention your use case for that file. I would prefer to add it as a separate package with same versioning (e.g. `@material-symbols/metadata`) as it is common to all packages (fonts, svgs).

**Comment by Baelx** [comment]
A use-case would be providing an icon picker to the user similar to how you've set up in the demo. Is there any other way to get a comprehensive, up-to-date JSON list of all symbols that's somewhat human readable?

**Comment by marella** [comment]
Sorry for the late response. I will include it in a separate package.

**Comment by marella** [comment]
Published in [@material-symbols/metadata](https://www.npmjs.com/package/@material-symbols/metadata)
