### ISSUE TITLE
SVG icon won't scale as expected

### ISSUE THREAD

**Issue by marcomtr** [marella/material-symbols#5]
See here
https://codepen.io/marcomtr/pen/JjZjrNK

**Comment by marella** [comment]
Looks like all material symbols are missing the `viewBox` property. Working example with `viewBox` property set: https://jsfiddle.net/yq5befz7/
Will ask on official repo if it can be added at the source (fonts CDN), otherwise will add it in this package.

**Comment by marella** [comment]
Added `viewBox` to SVGs in the latest release 0.4.0
